### PR TITLE
force to right layout on left to right phone languags

### PR DESCRIPTION
**Pull request by pishguy**

### CODE REVIEW

**Comment by mohamed6996** [comment]
Thank you for your contribution! 
but there is a problem with your code. the Icon is always on the right!
when i use  `slideGravity:EdgeAlert.LEFT, or  slideGravity:EdgeAlert.LEFT`
it just changes the title and description alignment, but the icon itself is always on the right

**Comment by mohamed6996** [comment]
I think there is no practical use case to force to right layout on ltr phone.
I think the required feature is to support rtl layout only.
thanx D:

**Comment by pishguy** [comment]
@mohamed6996 yes, its only option for ```rtl``` applications on ```ltr``` phone languages

**Comment by mohamed6996** [comment]
Thank you @MahdiPishguy  for your interest in EdgeAlert! 
Like i said, there is no practical use case for this feature. It will be odd to `ltr `user to see the alert from `rtl `and the whole app is `ltr `

**Pull request closed without merging**
